[jumphost]
# Substitua pelo IP Público gerado pelo Terraform
10.0.0.1 ansible_user=root
# Nota: Após a primeira execução e instalação do Tailscale/Hardening, 
# o acesso deve ser feito apenas via VPN (IP 100.x.x.x) e o usuário 'root' será desativado.
