---
- name: Setup and Harden Jumphost
  hosts: jumphost
  become: yes
  vars:
    # Variáveis que podem ser sobrescritas ao rodar o comando ansible-playbook
    cloudflare_tunnel_token: "SEU_TOKEN_DO_TUNEL_AQUI"
    tailscale_auth_key: "SUA_CHAVE_AUTH_AQUI"
  
  roles:
    - hardening
    - docker
    - cloudflare
    - jenkins
    - guacamole
