---
- name: Add Cloudflare repository GPG key
  shell: curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
  args:
    creates: /usr/share/keyrings/cloudflare-main.gpg

- name: Add Cloudflare repository
  shell: echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | tee /etc/apt/sources.list.d/cloudflared.list
  args:
    creates: /etc/apt/sources.list.d/cloudflared.list

- name: Update apt cache and install cloudflared
  apt:
    name: cloudflared
    state: present
    update_cache: yes

- name: Install and start Cloudflared service (if token is provided)
  command: cloudflared service install {{ cloudflare_tunnel_token }}
  when: cloudflare_tunnel_token != "SEU_TOKEN_DO_TUNEL_AQUI"
  ignore_errors: yes # Evita falhar caso o serviço já esteja instalado
